### ISSUE TITLE
Idea: Showing spl_object_id instead of spl_object_hash in exporter output for objects?

### ISSUE THREAD

**Issue by TysonAndre** [sebastianbergmann/exporter#39]
The latest release of this repo supports php >=8.0 - older releases had to support php 7.1 and below. In a future release of the repo, would it make sense to use [spl_object_id](https://php.net/spl_object_id) from php 7.2 instead?

It seems easier to me to distinguish small decimal numbers than 32-character hashes when reading an object.

I could work on an implementation and updating tests if you are interested in doing that and would prefer that for v5

-----

Existing behavior:

```
stdClass Object &0000000003a66dcc0000000025e723e2 (
    'self' => stdClass Object &0000000003a66dcc0000000025e723e2
)
```

Proposed: `&id` or `#id`  (like var_dump)

```php
stdClass Object &5 (
    'self' => stdClass Object &5
)
```

**Comment by sebastianbergmann** [comment]
Makes sense to me.
